[package]
name = "vision-stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "vision_stream"
crate-type = ["cdylib"]

[dependencies]
glib = "0.18.4"
gst = { package = "gstreamer", version = "0.21.2" }
gst-app = { package = "gstreamer-app", version = "0.21.2" }
numpy = "0.19.0"
pyo3 = "0.19.0"
